name: time_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.1
  - bleach=3.1.0
  - blinker=1.4
  - boto=2.49.0
  - boto3=1.9.168
  - botocore=1.12.168
  - bz2file=0.98
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - docutils=0.14
  - entrypoints=0.3
  - freetype=2.10.0
  - gensim=3.4.0
  - idna=2.8
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jmespath=0.9.4
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libffi=3.2.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.0.10
  - llvm-openmp=8.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mistune=0.8.4
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - nltk=3.2.5
  - notebook=5.7.8
  - numpy=1.16.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openblas=0.3.3
  - openssl=1.1.1b
  - pandas=0.24.2
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - patsy=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyjwt=1.7.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyrsistent=0.15.2
  - pysocks=1.7.0
  - python=3.7.3
  - python-crfsuite=0.9.6
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.1
  - readline=7.0
  - requests=2.22.0
  - requests-oauthlib=1.2.0
  - s3transfer=0.2.1
  - scikit-learn=0.20.3
  - scipy=1.2.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - six=1.12.0
  - smart_open=1.8.4
  - sqlite=3.28.0
  - statsmodels=0.9.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.2
  - tqdm=4.32.1
  - traitlets=4.3.2
  - twython=3.7.0
  - urllib3=1.24.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.3
  - pip:
    - future==0.17.1
    - nose==1.3.7
    - pybasicbayes==0.2.2

